name = "WordCloud"
uuid = "6385f0a0-cb03-45b6-9089-4e0acc74b26b"
authors = ["guoyongzhi <guo-yong-zhi@outlook.com>"]
version = "0.9.2"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Stuffing = "4175e07e-e5b7-423e-8796-3ea7f6d48281"

[compat]
ColorSchemes = "3"
Colors = "0.9, 0.10, 0.11, 0.12"
FileIO = "1"
ImageTransformations = "0.5, 0.6, 0.7, 0.8, 0.9"
Luxor = "2.8"
Stuffing = "0.6"
julia = "1.2"
